./
|-- __init__.py
|-- __pycache__/
|   |-- __init__.cpython-312.pyc
|   |-- main.cpython-312.pyc
|-- api/
|   |-- __deps.py
|   |-- __init__.py
|   |-- __pycache__/
|   |   |-- __init__.cpython-312.pyc
|   |-- v1/
|   |   |-- __init__.py
|   |   |-- __pycache__/
|   |   |   |-- __init__.cpython-312.pyc
|   |   |   |-- router.cpython-312.pyc
|   |   |-- routes/
|   |   |   |-- __init__.py
|   |   |   |-- __pycache__/
|   |   |   |   |-- __init__.cpython-312.pyc
|   |   |   |   |-- auth.cpython-312.pyc
|   |   |   |   |-- router.cpython-312.pyc
|   |   |   |   |-- user.cpython-312.pyc
|   |   |   |-- auth.py
|   |   |   |-- tags.py
|   |   |   |-- tasks.py
|   |   |   |-- user.py
|-- config/
|   |-- __init__.py
|   |-- __pycache__/
|   |   |-- __init__.cpython-312.pyc
|   |   |-- database.cpython-312.pyc
|   |   |-- settings.cpython-312.pyc
|   |-- database.py
|   |-- settings.py
|-- core/
|   |-- __pycache__/
|   |   |-- constants.cpython-312.pyc
|   |   |-- exceptions.cpython-312.pyc
|   |   |-- messages.cpython-312.pyc
|   |   |-- security.cpython-312.pyc
|   |   |-- validators.cpython-312.pyc
|   |-- constants.py
|   |-- exceptions.py
|   |-- messages.py
|   |-- result.py
|   |-- security.py
|   |-- services/
|   |   |-- __init__.py
|   |   |-- __pycache__/
|   |   |   |-- __init__.cpython-312.pyc
|   |   |   |-- auth_service.cpython-312.pyc
|   |   |   |-- base_service.cpython-312.pyc
|   |   |   |-- user_service.cpython-312.pyc
|   |   |-- auth_service.py
|   |   |-- base_service.py
|   |   |-- tags_service.py
|   |   |-- task_service.py
|   |   |-- user_service.py
|   |-- validators.py
|-- folder.py
|-- main.py
|-- middlewares/
|   |-- __init__.py
|   |-- __pycache__/
|   |   |-- __init__.cpython-312.pyc
|   |   |-- error_middleware.cpython-312.pyc
|   |   |-- logging_middleware.cpython-312.pyc
|   |-- error_middleware.py
|   |-- logging_middleware.py
|-- models/
|   |-- __init__.py
|   |-- __pycache__/
|   |   |-- __init__.cpython-312.pyc
|   |   |-- base.cpython-312.pyc
|   |   |-- tag.cpython-312.pyc
|   |   |-- task.cpython-312.pyc
|   |   |-- user.cpython-312.pyc
|   |-- base.py
|   |-- tag.py
|   |-- task.py
|   |-- user.py
|-- repositories/
|   |-- __init__.py
|   |-- __pycache__/
|   |   |-- __init__.cpython-312.pyc
|   |   |-- base.cpython-312.pyc
|   |   |-- tag_repository.cpython-312.pyc
|   |   |-- task_repository.cpython-312.pyc
|   |   |-- user_repository.cpython-312.pyc
|   |-- base.py
|   |-- tag_repository.py
|   |-- task_repository.py
|   |-- user_repository.py
|-- schemas/
|   |-- __init__.py
|   |-- __pycache__/
|   |   |-- __init__.cpython-312.pyc
|   |   |-- common.cpython-312.pyc
|   |   |-- error.cpython-312.pyc
|   |   |-- tag.cpython-312.pyc
|   |   |-- task.cpython-312.pyc
|   |   |-- user.cpython-312.pyc
|   |-- common.py
|   |-- error.py
|   |-- tag.py
|   |-- task.py
|   |-- user.py
|-- structure.txt
|-- utils/
|   |-- __init__.py
|   |-- __pycache__/
|   |   |-- __init__.cpython-312.pyc
|   |   |-- enum.cpython-312.pyc
|   |   |-- exceptions.cpython-312.pyc
|   |-- enum.py